apiVersion: v1
kind: Service
metadata:
  name: calculator-microservice-service
spec:
  selector:
    app: calculator-microservice
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 3000
      nodePort: 31110
